<h2>Generate Population Report</h2>
<form method="POST" action="{{ route('admin.reports.population') }}">
    @csrf
    Report Name: <input type="text" name="report_name" required><br><br>

    From: <input type="date" name="date_from" required><br><br>
    To: <input type="date" name="date_to" required><br><br>

    <!-- additional population filters -->
    <div>
        <label>Age Group:</label>
        <select name="age_group">
            <option value="">All</option>
            <option value="children" {{ old('age_group')=='children'?'selected':'' }}>Children (0–12)</option>
            <option value="youth" {{ old('age_group')=='youth'?'selected':'' }}>Youth (13–17)</option>
            <option value="adults" {{ old('age_group')=='adults'?'selected':'' }}>Adults (18–59)</option>
            <option value="senior" {{ old('age_group')=='senior'?'selected':'' }}>Senior Citizens (60+)</option>
        </select>
    </div>
    <div>
        <label>Gender:</label>
        <select name="gender">
            <option value="">All</option>
            <option value="male" {{ old('gender')=='male'?'selected':'' }}>Male</option>
            <option value="female" {{ old('gender')=='female'?'selected':'' }}>Female</option>
        </select>
    </div>
    <div>
        <label>Street:</label>
        <select name="street">
            <option value="">All</option>
            @foreach($streets as $streetName)
                <option value="{{ $streetName }}" {{ old('street') == $streetName ? 'selected' : '' }}>{{ $streetName }}</option>
            @endforeach
        </select>
    </div>
    <div>
        <label>Parent Status:</label>
        <select name="parent">
            <option value="">All</option>
            <option value="yes" {{ old('parent')=='yes'?'selected':'' }}>Yes</option>
            <option value="no" {{ old('parent')=='no'?'selected':'' }}>No</option>
            <option value="single" {{ old('parent')=='single'?'selected':'' }}>Single Parent</option>
        </select>
    </div>
    <div>
        <label>Civil Status:</label>
        <select name="civil_status">
            <option value="">All</option>
            <option value="single" {{ old('civil_status')=='single'?'selected':'' }}>Single</option>
            <option value="married" {{ old('civil_status')=='married'?'selected':'' }}>Married</option>
            <option value="widowed" {{ old('civil_status')=='widowed'?'selected':'' }}>Widowed</option>
            <option value="divorced" {{ old('civil_status')=='divorced'?'selected':'' }}>Divorced</option>
        </select>
    </div>
    <br>
    <button type="submit">Generate</button>
</form>

<hr>

<h2>Generate Blotter Report</h2>
<form method="POST" action="{{ route('admin.reports.blotter') }}">
    @csrf
    Report Name: <input type="text" name="report_name" required><br><br>

    From: <input type="date" name="date_from" required><br><br>
    To: <input type="date" name="date_to" required><br><br>
    <!-- only finished cases are included by backend -->
    <button type="submit">Generate</button>
</form>

<hr>

<h2>Generate Certificate Report</h2>
<form method="POST" action="{{ route('admin.reports.certificate') }}">
    @csrf
    Report Name: <input type="text" name="report_name" required><br><br>

    From: <input type="date" name="date_from" required><br><br>
    To: <input type="date" name="date_to" required><br><br>
    <!-- only released certificates are included by backend -->
    <button type="submit">Generate</button>
</form>

<hr>

<h2>Generated Reports</h2>

<table border="1">
    <tr>
        <th>Report Name</th>
        <th>Type</th>
        <th>Generated By</th>
        <th>Date</th>
        <th>Total Records</th>
        <th>Action</th>
    </tr>

    @foreach($reports as $report)
    <tr>
        <td>{{ $report->report_name }}</td>
        <td>{{ ucfirst($report->report_type) }}</td>
        <td>{{ $report->generated_by }}</td>
        <td>{{ $report->created_at }}</td>
        <td>{{ $report->total_records }}</td>
        <td>
            <a href="{{ route('admin.reports.view', $report->id) }}">View</a>
        </td>
    </tr>
    @endforeach
</table>
